### PR TITLE
Removed org_name in the update_org

### PR DESCRIPTION
**Pull request by anusuyar**
This change is [Reviewable](https://reviewable.io/reviews/anusuyar/vcd-cli/6)

### CODE REVIEW

**Comment by pacogomez** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/org.py, line 208 at r1](https://reviewable.io:443/reviews/anusuyar/vcd-cli/6#-L-n4hL0pF0sWmiIYUqi:-L-n4hL1xTgMNm-p7GPo:bo187qg) ([raw file](https://github.com/anusuyar/vcd-cli/blob/1e4d35d1aab8e0e8b90bf2914b6ef0fd833ba35d/vcd_cli/org.py#L208)):*
> ```Python
>         client = ctx.obj['client']
>         org_href = client.get_org_by_name(name).get('href')
>         org = Org(client, org_href)
> ```

It should use the `resource` param in the `Org` constructor

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/vcd-cli/6)*

**Comment by anusuyar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/org.py, line 208 at r1](https://reviewable.io:443/reviews/anusuyar/vcd-cli/6#-L-n4hL0pF0sWmiIYUqi:-L-n86U05K9iGmgrxzSs:b-896fix) ([raw file](https://github.com/anusuyar/vcd-cli/blob/1e4d35d1aab8e0e8b90bf2914b6ef0fd833ba35d/vcd_cli/org.py#L208)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

It should use the `resource` param in the `Org` constructor
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/vcd-cli/6)*

**Comment by pacogomez** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/vcd-cli/6#-:-L-n8UNmgCguY5vIpo7e:bnfp4nl)*

**Comment by pacogomez** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/vcd-cli/6)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/vcd-cli/6#-:-L-nE6hof8AVMY65y6mA:bnfp4nl)*

**Pull request closed without merging**
