### PR TITLE
Enable/Disable Org, User. Add --enable option for create org.

### PR DESCRIPTION
**Pull request by anusuyar**
…org_name>' command)

2. Add new option '--enable' to enable org during creation.
3. Enable/disable user which was already created. (via 'vcd user update <user_name>' command)

Creating a new Pull request as the branch develop had problems with merges.
https://reviewable.io/reviews/anusuyar/vcd-cli/3

---
This change is [Reviewable](https://reviewable.io/reviews/anusuyar/vcd-cli/4)

### CODE REVIEW

**Comment by rocknes** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[vcd_cli/org.py, line 49 at r1](https://reviewable.io:443/reviews/anusuyar/vcd-cli/4#-L-dr3KnFl3IKBqrZLnk:-L-dr3KnFl3IKBqrZLnl:biw8fp4) ([raw file](https://github.com/anusuyar/vcd-cli/blob/1a2280820a74ea6824ab08b85ab35b6d18938b80/vcd_cli/org.py#L49)):*
> ```Python
>             Delete organization 'my-org-name'
> \b
>         vcd org update my-org-name
> ```

This looks like a bad example, it doesn't specify what we are updating.

---

*[vcd_cli/org.py, line 200 at r1](https://reviewable.io:443/reviews/anusuyar/vcd-cli/4#-L-drhjUF9632yUslEbO:-L-drhjVjWH9kj-dl5ii:bsetaa2) ([raw file](https://github.com/anusuyar/vcd-cli/blob/1a2280820a74ea6824ab08b85ab35b6d18938b80/vcd_cli/org.py#L200)):*
> ```Python
>                 metavar='<name>',
>                 required=True)
> @click.option('--enable/--disable', 'is_enabled', default=None,
> ```

Let's follow the standard we have in place for click options/argument : One arg on one line.

Also how is --enabled and --disabled mapped to True of False value of is_enabled? We are not specifying the type here. Can you please clarify?

---

*[vcd_cli/org.py, line 207 at r1](https://reviewable.io:443/reviews/anusuyar/vcd-cli/4#-L-dsLq5PKh3_TboHrz0:-L-dsLq5PKh3_TboHrz1:bkzr1ae) ([raw file](https://github.com/anusuyar/vcd-cli/blob/1a2280820a74ea6824ab08b85ab35b6d18938b80/vcd_cli/org.py#L207)):*
> ```Python
>         in_use_org_href = ctx.obj['profiles'].get('org_href')
>         org = Org(client, in_use_org_href)
>         result = org.update_org(name, is_enabled)
> ```

Set the variable names too. Will reduce confusion once we have more params added to the update_org function.

---

*[vcd_cli/user.py, line 28 at r1](https://reviewable.io:443/reviews/anusuyar/vcd-cli/4#-L-dsa1u-ljzcPt_ukQF:-L-dsa1u-ljzcPt_ukQG:b-1fay5u) ([raw file](https://github.com/anusuyar/vcd-cli/blob/1a2280820a74ea6824ab08b85ab35b6d18938b80/vcd_cli/user.py#L28)):*
> ```Python
>            deletes user with username "my user" from the current organization. Will also delete vApps owned by the user. If user has running vApps, this command will result in error.
> \b
>         vcd user update 'my user' 
> ```

Again, the example lacks what we are updating in the user resource!

---

*[vcd_cli/user.py, line 144 at r1](https://reviewable.io:443/reviews/anusuyar/vcd-cli/4#-L-dsnBnM45WDv67u4N1:-L-dsnBnM45WDv67u4N2:bjsvyd9) ([raw file](https://github.com/anusuyar/vcd-cli/blob/1a2280820a74ea6824ab08b85ab35b6d18938b80/vcd_cli/user.py#L144)):*
> ```Python
>         role = org.get_role(role_name)
>         role_href = role.get('href')
>         result = org.create_user(user_name, password, role_href, full_name,
> ```

It's always better to explicitly spill the param names instead of relying on the order of the args.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/vcd-cli/4)*

**Comment by anusuyar** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[vcd_cli/org.py, line 49 at r1](https://reviewable.io:443/reviews/anusuyar/vcd-cli/4#-L-dr3KnFl3IKBqrZLnk:-L-dvJS6aroSnRoPSOTy:bwqcpk3) ([raw file](https://github.com/anusuyar/vcd-cli/blob/1a2280820a74ea6824ab08b85ab35b6d18938b80/vcd_cli/org.py#L49)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This looks like a bad example, it doesn't specify what we are updating.
</blockquote></details>

It says the command is used to update the org. To know what params can be updated, the user can invoke help in the command and know what parameters can be updated. This way, when we add 10 more params to update command, we don't have to add each one of them in the example.  vcd org update --help will list them all.

(vcd-cli) λ vcd org update --help
Usage: vcd org update [OPTIONS] <name>

Options:
  --enable / --disable  enable/disable the org

---

*[vcd_cli/org.py, line 200 at r1](https://reviewable.io:443/reviews/anusuyar/vcd-cli/4#-L-drhjUF9632yUslEbO:-L-du4ZN7_zsc45Qe3mf:b-nuzevl) ([raw file](https://github.com/anusuyar/vcd-cli/blob/1a2280820a74ea6824ab08b85ab35b6d18938b80/vcd_cli/org.py#L200)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Let's follow the standard we have in place for click options/argument : One arg on one line.

Also how is --enabled and --disabled mapped to True of False value of is_enabled? We are not specifying the type here. Can you please clarify?
</blockquote></details>

Its a feature of click framework.

Boolean Flags
Boolean flags are options that can be enabled or disabled. This can be accomplished by defining two flags in one go separated by a slash (/) for enabling or disabling the option. (If a slash is in an option string, Click automatically knows that it’s a boolean flag and will pass is_flag=True implicitly.) Click always wants you to provide an enable and disable flag so that you can change the default later.

Example:

import sys

@click.command()
@click.option('--shout/--no-shout', default=False)
def info(shout):
    rv = sys.platform
    if shout:
        rv = rv.upper() + '!!!!111'
    click.echo(rv)
And on the command line:

$ info --shout
LINUX2!!!!111
$ info --no-shout
linux2
http://click.pocoo.org/5/options/

---

*[vcd_cli/org.py, line 207 at r1](https://reviewable.io:443/reviews/anusuyar/vcd-cli/4#-L-dsLq5PKh3_TboHrz0:-L-dxNPPauRe7jRnN70m:b-896fix) ([raw file](https://github.com/anusuyar/vcd-cli/blob/1a2280820a74ea6824ab08b85ab35b6d18938b80/vcd_cli/org.py#L207)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Set the variable names too. Will reduce confusion once we have more params added to the update_org function.
</blockquote></details>

Done.

---

*[vcd_cli/user.py, line 28 at r1](https://reviewable.io:443/reviews/anusuyar/vcd-cli/4#-L-dsa1u-ljzcPt_ukQF:-L-dwEjdaC31fcuA_CsK:b-m3tdjt) ([raw file](https://github.com/anusuyar/vcd-cli/blob/1a2280820a74ea6824ab08b85ab35b6d18938b80/vcd_cli/user.py#L28)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Again, the example lacks what we are updating in the user resource!
</blockquote></details>

Replied to the other comment.

---

*[vcd_cli/user.py, line 144 at r1](https://reviewable.io:443/reviews/anusuyar/vcd-cli/4#-L-dsnBnM45WDv67u4N1:-L-dwoc8F2EJSyWmhMbL:bu8s1mh) ([raw file](https://github.com/anusuyar/vcd-cli/blob/1a2280820a74ea6824ab08b85ab35b6d18938b80/vcd_cli/user.py#L144)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

It's always better to explicitly spill the param names instead of relying on the order of the args.
</blockquote></details>

I will address changes for create_user in a different CL. Don't want to make major changes to code not related to this original code changes. Made changes to update_user

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/vcd-cli/4)*

**Comment by anusuyar** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[vcd_cli/org.py, line 49 at r1](https://reviewable.io:443/reviews/anusuyar/vcd-cli/4#-L-dr3KnFl3IKBqrZLnk:-L-hP4pEKQ6psDUesZPI:b-bvizr2) ([raw file](https://github.com/anusuyar/vcd-cli/blob/1a2280820a74ea6824ab08b85ab35b6d18938b80/vcd_cli/org.py#L49)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

It says the command is used to update the org. To know what params can be updated, the user can invoke help in the command and know what parameters can be updated. This way, when we add 10 more params to update command, we don't have to add each one of them in the example.  vcd org update --help will list them all.

(vcd-cli) λ vcd org update --help
Usage: vcd org update [OPTIONS] <name>

Options:
  --enable / --disable  enable/disable the org
</blockquote></details>

Done. Changed the example now.

---

*[vcd_cli/user.py, line 28 at r1](https://reviewable.io:443/reviews/anusuyar/vcd-cli/4#-L-dsa1u-ljzcPt_ukQF:-L-hOmYle25eO-4BSUGV:b-lgk2os) ([raw file](https://github.com/anusuyar/vcd-cli/blob/1a2280820a74ea6824ab08b85ab35b6d18938b80/vcd_cli/user.py#L28)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Replied to the other comment.
</blockquote></details>

Changed the example.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/vcd-cli/4)*

**Comment by rocknes** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/vcd-cli/4#-:-L-hZdwy4JEgo6Aqiq3R:bnfp4nl)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/vcd-cli/4#-:-L-hck7RfTqTpGOeT7Pe:bnfp4nl)*

**Pull request closed without merging**
