### PR TITLE
Changing the args format to pass param name and value.

### PR DESCRIPTION
**Pull request by anusuyar**
This change is [Reviewable](https://reviewable.io/reviews/anusuyar/vcd-cli/5)

### CODE REVIEW

**Comment by pacogomez** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/vcd-cli/5#-:-L-iUDBGaLtRIOEDWXK0:bnfp4nl)*

**Comment by pacogomez** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/vcd-cli/5)*

**Comment by rocknes** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/vcd-cli/5#-:-L-idCdxRnudB86xr1YX:bnfp4nl)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/vcd-cli/5#-:-L-idPhnvzgY5IPw8jl5:bnfp4nl)*

**Pull request closed without merging**
